
export const ERA_SUGGESTIONS: Record<string, string[]> = {
    Anniversary: [
        "Best leveling route for fresh Anniversary server?",
        "What changes in the TBC pre-patch?",
        "Best class for Anniversary fresh start?",
        "AoE mage leveling spots Classic",
        "How to prepare for TBC launch?",
        "Fastest way to level 1-60 in Anniversary?",
        "Hunter pet leveling guide",
        "Warlock leveling drain tank build",
        "Where to farm Runecloth?",
        "Best addons for Anniversary realms",
        "Dungeon cleave groups setup",
        "Paladin AoE farming Zul'Farrak",
        "Shaman totem twisting guide",
        "Weapon skill leveling guide",
        "Best professions for gold making early",
        "Fishing expert guide Stranglethorn",
        "Rogue pickpocket farming BRD",
        "Warrior tanking RFC to UBRS guide",
        "Priest healing rotation low level",
        "Druid feral vs balance leveling",
        "Where is Mankrik's wife?",
        "Horde vs Alliance population Anniversary",
        "Best race for Priest?",
        "Wand progression guide 1-60",
        "Attunement guide for Onyxia",
        "Molten Core raid preparation",
        "Pre-raid BiS for Fury Warrior",
        "Best gold farm for level 40 mount?",
        "Where to find Rexxar?",
        "Scarlet Monastery cathedral solo guide",
        "Zul'Gurub tiger boss tactics",
        "Alterac Valley reputation rewards",
        "Warsong Gulch flag carrying tips",
        "Arathi Basin node strat",
        "Engineering gadgets for PvP",
        "Blacksmithing specialization guide",
        "Leatherworking tribal vs elemental",
        "Tailoring robe of the archmage mats",
        "Enchanting crusader formula drop",
        "Herbalism black lotus spawn points",
        "Mining rich thorium vein route",
        "Skinning devilsaur leather farm",
        "Cooking savory deviate delight recipe",
        "First aid runecloth bandage trainer",
        "Lockpicking leveling guide 1-300",
        "Riding skill trainer locations",
        "Macro guide for warriors",
        "UI setup for healers",
        "Keybinding tips for beginners",
        "Hardcore leveling tips"
    ],
    Classic: [
        "Molten Core attunement walkthrough",
        "Onyxia key questline Alliance",
        "Onyxia key questline Horde",
        "Blackwing Lair suppression room tactics",
        "Nefarian class calls explained",
        "Ahn'Qiraj war effort supplies list",
        "C'Thun eye beam positioning",
        "Naxxramas 40 attunement cost",
        "Thaddius polarity shift weakaura",
        "Sapphiron frost resistance gear check",
        "Best gold farm for Epic Mount?",
        "Dire Maul East jump run guide",
        "Tribute run Dire Maul North",
        "Scholomance key quest guide",
        "Stratholme living side pulls",
        "Upper Blackrock Spire 10 man guide",
        "BiS pre-raid gear for Rogue",
        "Mage AoE farming ZG crocodiles",
        "Hunter tribute run visual guide",
        "Warlock DM East solo farm",
        "Paladin Lasher farm DM East",
        "Best PvP ranking bracket calculator",
        "Rank 14 weapons cost and stats",
        "Alterac Valley exalted rep rewards",
        "Warsong Gulch premade strategies",
        "Arathi Basin 5 cap strategy",
        "Engineering grenades in PvP",
        "Free Action Potion usage tips",
        "Living Action Potion vs Restorative",
        "Best consumables for raiding",
        "World buffs route and timing",
        "Songflower Serenade location",
        "Darkmoon Faire buff cooldown",
        "Rallying Cry of the Dragonslayer timer",
        "Warchief's Blessing drop cooldown",
        "Zandalar Spirit buff guide",
        "Sayge's Dark Fortune buff list",
        "Dark Iron Residue turn in",
        "Thorium Brotherhood rep guide",
        "Timbermaw Hold rep farming",
        "Argent Dawn rep farming stratification",
        "Hydraxian Waterlords rep for douse",
        "Cenarion Circle rep rewards",
        "Brood of Nozdormu rep grind",
        "Zandalar Tribe rep coin turn ins",
        "Frostsaber Trainer mount grind",
        "Winterspring Frostsaber rep guide",
        "Ravager trainer location",
        "Broken Tooth spawn timer",
        "Lupos spawn timer"
    ],
    TBC: [
        "Karazhan attunement flowchart",
        "Heroic dungeon key requirements",
        "Flying mount gold cost TBC",
        "Netherwing Drake reputation guide",
        "Skyguard reputation daily route",
        "Ogri'la reputation unlock quests",
        "Shattered Sun Offensive dailies",
        "Isle of Quel'Danas portal location",
        "Magister's Terrace heroic guide",
        "Sunwell Plateau radiator strat",
        "M'uru entropy boss guide",
        "Kil'jaeden darkness phase tips",
        "Black Temple attunement steps",
        "Illidan Stormrage phase guide",
        "Hyjal Summit wave management",
        "Archimonde air burst safety",
        "Vashj tainted core macro",
        "Kael'thas weapons usage guide",
        "Gruul's Lair grow stack limit",
        "Magtheridon cube clicker rotation",
        "Best Primal farming spots",
        "Primal Fire farming Throne of KJ",
        "Primal Water farming Skettis",
        "Primal Mana farming Netherstorm",
        "Primal Air farming Shadowmoon",
        "Primal Earth farming Nagrand",
        "Primal Life farming Zangarmarsh",
        "Primal Shadow farming Nagrand",
        "Aldor or Scryer for Mage?",
        "Aldor or Scryer for Rogue?",
        "Aldor or Scryer for Paladin?",
        "Aldor or Scryer for Priest?",
        "Aldor or Scryer for Warrior?",
        "Best Jewelcrafting gems TBC",
        "Leatherworking drums of battle meta",
        "Blacksmithing weapons specialization",
        "Tailoring spellfire set bonus",
        "Engineering mote extractor guide",
        "Alchemy transmute mastery quest",
        "Enchanting ring enchants",
        "Arena Season 1 Gladiator cutoff",
        "Arena Season 2 Merciless gear",
        "Arena Season 3 Vengeful gear",
        "Arena Season 4 Brutal gear",
        "Druid flight form questline",
        "Paladin epic mount questline",
        "Warlock epic mount questline",
        "Shaman totems TBC changes",
        "Hunter steady shot macro",
        "Shadow Priest mana battery guide"
    ],
    WotLK: [
        "How to unlock Cold Weather Flying?",
        "Heirloom gear vendor locations",
        "Dual Specialization cost and trainer",
        "Death Knight starting zone guide",
        "Best DK leveling spec Blood or Unholy?",
        "Inscription profession leveling guide",
        "Glyph of Major Healing recipe",
        "Sons of Hodir reputation unlock",
        "Shoulder enchants WotLK guide",
        "Knights of the Ebon Blade rep tabard",
        "Argent Crusade rep tabard location",
        "Kirin Tor rep tabard location",
        "Wyrmrest Accord rep tabard location",
        "Naxxramas 25 tactics overview",
        "Ulduar hard modes trigger guide",
        "Algalon the Observer access key",
        "Yogg-Saron 0 lights strategy",
        "Trial of the Crusader invisible horse",
        "Icecrown Citadel wing unlock order",
        "Lich King defile positioning",
        "Shadowmourne questline shards",
        "Val'anyr fragments drop rate",
        "Time-Lost Proto Drake spawn points",
        "Storm Peaks rare spawns map",
        "Sholazar Basin Loque'nahak spawn",
        "Dalaran sewer mount fishing",
        "Wintergrasp pvp timer and rewards",
        "Vault of Archavon boss loot table",
        "Strand of the Ancients bg guide",
        "Isle of Conquest siege engine tips",
        "Best heroic dungeon for emblems",
        "Random Dungeon Finder release date",
        "Titan Rune dungeon affix list",
        "Defogging the Dalaran lens",
        "Achievements guide Glory of the Raider",
        "Glory of the Ulduar Raider mounts",
        "Glory of the Icecrown Raider mounts",
        "Loremaster of Northrend checklist",
        "Explorer of Northrend route",
        "Kalu'ak fishing pole reputation",
        "Oracles vs Frenzyheart choice",
        "Green Proto Drake egg chance",
        "Polar Bear mount daily quest",
        "Mammoth mount vendor cost",
        "Repair mount vendor Dalaran",
        "Jewelcrafting daily quest location",
        "Cooking daily quest spice bag",
        "Fishing daily quest rewards",
        "Borean Tundra vs Howling Fjord leveling",
        "Grizzly Hills music playlist",
        "Zul'Drak amphitheater of anguish"
    ],
    Retail: [
        "The War Within season 1 tier list",
        "Best Mythic+ dungeon for crests?",
        "Great Vault unlock requirements",
        "Catalyst charge accrual rate",
        "Delves guide how to unlock tiers",
        "Brann Bronzebeard talent build",
        "Earthen allied race unlock quest",
        "Khaz Algar flight paths map",
        "Dornogal capital city guide",
        "Profession stats priority guide",
        "Crafting orders system explained",
        "Spark of Omens cap catchup",
        "Algari weaving cloth farm",
        "Storm dust enchanting farm",
        "Bismuth mining route",
        "Mycobloom herbalism route",
        "Fishing derby Hallowfall guide",
        "Renown rewards Council of Dornogal",
        "Renown rewards Assembly of the Deeps",
        "Renown rewards Hallowfall Arathi",
        "Renown rewards The Severed Threads",
        "Notoriety mechanic explained",
        "Rumors maps for Nerubians",
        "Nerub-ar Palace raid entrance",
        "Queen Ansurek boss tactics",
        "Silken Court heroic guide",
        "Ky'veza void phase positioning",
        "Rashanan flying mechanics",
        "Bloodbound Horror mount drop",
        "Skyriding glyph locations TWW",
        "Dynamic flight vs steady flight",
        "Warbands bank access quest",
        "Warbound gear usage guide",
        "Transmog collection changes TWW",
        "Cross-realm guild invite how to",
        "Mythic+ affixes rotation season 1",
        "Xal'atath interactions dialogue",
        "Best addons for The War Within",
        "WeakAuras for Season 1 dungeons",
        "Details damage meter configuration",
        "Raider.IO score calculation",
        "Warcraft Logs Uploader setup",
        "Simcraft raidbots usage guide",
        "Pawn stat weights string export",
        "Method Dungeon Tools route import",
        "OmniCD party cooldowns tracker",
        "BigWigs vs DBM for TWW",
        "Plater nameplates profile import",
        "ElvUI profile for healer",
        "VuhDo clicking setup guide"
    ]
};
